name: JoinLeave
version: 1.2.2
main: JoinLeave\Main
api: [4.0.0, 5.0.0]
author: GeistFan
command:
  tjl:
    description: Testet ob JoinLeave aktiv ist.
    permission: JoinLeaveTest.cmd

permissons:
  JoinLeaveTest.cmd:
    default: op
    description: Darf /tjl benutzen.
